name: Autogern Hourly

on:
  workflow_dispatch:
  schedule:
    - cron: "5 * * * *"

permissions:
  contents: write

concurrency:
  group: autogern-hourly
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      HF_HOME: ${{ github.workspace }}/.cache/huggingface
      TRANSFORMERS_CACHE: ${{ github.workspace }}/.cache/huggingface
      TORCH_HOME: ${{ github.workspace }}/.cache/torch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Cache model weights
        uses: actions/cache@v4
        with:
          path: |
            .cache/huggingface
            .cache/torch
          key: hf-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            hf-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run single autogern cycle
        env:
          FEEDS: ${{ secrets.AUTOGERN_FEEDS }}
          TOP_N: ${{ secrets.AUTOGERN_TOP_N }}
          IG_POST_ENABLED: ${{ secrets.AUTOGERN_IG_POST_ENABLED }}
          IG_USERNAME: ${{ secrets.AUTOGERN_IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.AUTOGERN_IG_PASSWORD }}
          IG_SESSION_PATH: out/ig_session.json
          IG_CAPTION_TEMPLATE: ${{ secrets.AUTOGERN_IG_CAPTION_TEMPLATE }}
          IG_HASHTAGS: ${{ secrets.AUTOGERN_IG_HASHTAGS }}
          CAPTION_SUMMARY_ENABLED: ${{ secrets.AUTOGERN_CAPTION_SUMMARY_ENABLED }}
          CAPTION_SUMMARY_MODEL: ${{ secrets.AUTOGERN_CAPTION_SUMMARY_MODEL }}
          CAPTION_SUMMARY_MIN_TOKENS: ${{ secrets.AUTOGERN_CAPTION_SUMMARY_MIN_TOKENS }}
          CAPTION_SUMMARY_MAX_TOKENS: ${{ secrets.AUTOGERN_CAPTION_SUMMARY_MAX_TOKENS }}
          CAPTION_SUMMARY_INPUT_MAX_CHARS: ${{ secrets.AUTOGERN_CAPTION_SUMMARY_INPUT_MAX_CHARS }}
          DEEPAI_KEYS: ${{ secrets.AUTOGERN_DEEPAI_KEYS }}
        run: |
          mkdir -p out
          python - <<'PY'
import autogern
autogern.one_hour_run()
PY

      - name: Commit updated state
        if: github.event_name != 'pull_request'
        run: |
          if [ ! -f out/state.json ]; then
            echo "State file not found; skipping commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add out/state.json
          if git diff --cached --quiet; then
            echo "No state changes to commit."
            exit 0
          fi
          git commit -m "chore: update autogern state [skip ci]"
          git push
